/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete: operations["UsersController_deleteMe"];
        options?: never;
        head?: never;
        patch: operations["UsersController_updateProfile"];
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UsersController_changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminUsersController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminUsersController_changeRole"];
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AdminUsersController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ModelsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ModelsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminModelsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/colors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ColorsController_list"];
        put?: never;
        post: operations["ColorsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/colors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ColorsController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PatternsController_list"];
        put?: never;
        post: operations["PatternsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patterns/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PatternsController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patterns/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PatternsController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patterns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PatternsController_get"];
        put?: never;
        post?: never;
        delete: operations["PatternsController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminPatternsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/patterns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminPatternsController_moderate"];
        trace?: never;
    };
    "/looks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LooksController_list"];
        put?: never;
        post: operations["LooksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/looks/gallery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LooksController_gallery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/looks/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LooksController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/looks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LooksController_get"];
        put: operations["LooksController_update"];
        post?: never;
        delete: operations["LooksController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/looks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminLooksController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/looks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminLooksController_moderate"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateProfileDto: {
            /** @example I sew, therefore I am. */
            bio?: string;
        };
        ChangePasswordDto: {
            currentPassword: string;
            newPassword: string;
        };
        DeleteMeDto: {
            /** @description Current password, as deletion confirmation */
            password: string;
        };
        AdminUserResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            /** @enum {string} */
            role: "USER" | "ADMIN";
            bio: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /** @description Owned content counts */
            counts: Record<string, never>;
        };
        PaginatedUsersResponse: {
            items: components["schemas"]["AdminUserResponse"][];
            total: number;
            page: number;
            limit: number;
        };
        UpdateRoleDto: {
            /** @enum {string} */
            role: "USER" | "ADMIN";
        };
        RegisterDto: {
            /**
             * Format: email
             * @example user@vogue.dev
             */
            email: string;
            /** @example password123 */
            password: string;
        };
        LoginDto: {
            /**
             * Format: email
             * @example user@vogue.dev
             */
            email: string;
            /** @example password123 */
            password: string;
        };
        ModelResponse: {
            /** Format: uuid */
            id: string;
            /** @example Basic T-Shirt */
            name: string;
            /** @enum {string} */
            kind: "TSHIRT" | "SHIRT" | "SKIRT" | "PANTS";
            /** @enum {string} */
            status: "PENDING" | "APPROVED" | "REJECTED";
            isPublic: boolean;
            /** @description null = official catalog item */
            ownerId: Record<string, never> | null;
            version: number;
            /** Format: date-time */
            createdAt: string;
        };
        PaginatedModelsResponse: {
            items: components["schemas"]["ModelResponse"][];
            total: number;
            page: number;
            limit: number;
        };
        ModelDetailResponse: {
            /** Format: uuid */
            id: string;
            /** @example Basic T-Shirt */
            name: string;
            /** @enum {string} */
            kind: "TSHIRT" | "SHIRT" | "SKIRT" | "PANTS";
            /** @enum {string} */
            status: "PENDING" | "APPROVED" | "REJECTED";
            isPublic: boolean;
            /** @description null = official catalog item */
            ownerId: Record<string, never> | null;
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** @description Short-lived presigned URL for the .glb binary */
            glbUrl: string;
        };
        ColorResponse: {
            /** Format: uuid */
            id: string;
            /** @example Navy */
            name: string;
            /** @example #1f3a5f */
            hex: string;
            /** @description null = global preset */
            ownerId: Record<string, never> | null;
            isPublic: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        PaginatedColorsResponse: {
            items: components["schemas"]["ColorResponse"][];
            total: number;
            page: number;
            limit: number;
        };
        CreateColorDto: {
            /** @example My Teal */
            name: string;
            /** @example #2a9d8f */
            hex: string;
        };
        PatternResponse: {
            /** Format: uuid */
            id: string;
            /** @example Houndstooth */
            name: string;
            /** @example image/png */
            mime: string;
            width: Record<string, never> | null;
            height: Record<string, never> | null;
            /** @description true once the upload passed validation */
            confirmed: boolean;
            /** @description Owner asked for this pattern to go public */
            publishRequested: boolean;
            /** @enum {string} */
            status: "PENDING" | "APPROVED" | "REJECTED";
            isPublic: boolean;
            /** @description null = global preset */
            ownerId: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /** @description Short-lived presigned URL of the gallery thumbnail */
            thumbnailUrl?: string;
        };
        PaginatedPatternsResponse: {
            items: components["schemas"]["PatternResponse"][];
            total: number;
            page: number;
            limit: number;
        };
        CreatePatternDto: {
            /** @example Houndstooth */
            name: string;
            /** @enum {string} */
            mime: "image/png" | "image/jpeg" | "image/webp";
        };
        CreatePatternResponse: {
            pattern: components["schemas"]["PatternResponse"];
            /** @description Presigned PUT URL: upload the raw image bytes here, then call /patterns/{id}/confirm */
            uploadUrl: string;
        };
        PatternDetailResponse: {
            /** Format: uuid */
            id: string;
            /** @example Houndstooth */
            name: string;
            /** @example image/png */
            mime: string;
            width: Record<string, never> | null;
            height: Record<string, never> | null;
            /** @description true once the upload passed validation */
            confirmed: boolean;
            /** @description Owner asked for this pattern to go public */
            publishRequested: boolean;
            /** @enum {string} */
            status: "PENDING" | "APPROVED" | "REJECTED";
            isPublic: boolean;
            /** @description null = global preset */
            ownerId: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /** @description Short-lived presigned URL of the gallery thumbnail */
            thumbnailUrl?: string;
            /** @description Short-lived presigned URL of the full-size image — the GarmentMaterial.patternUrl value */
            patternUrl: string;
        };
        ModerateDto: {
            /** @enum {string} */
            action: "approve" | "reject";
        };
        GarmentMaterialDto: {
            /** @example #9d2235 */
            color: string;
            /** @description Short-lived presigned URL, or null for color-only looks */
            patternUrl: Record<string, never> | null;
            /** @example 1 */
            patternScale: number;
        };
        LookResponse: {
            /** Format: uuid */
            id: string;
            /** @example Crimson tee */
            name: string;
            /** Format: uuid */
            garmentModelId: string;
            /** Format: uuid */
            colorId: Record<string, never> | null;
            /** Format: uuid */
            patternId: Record<string, never> | null;
            /** @description Resolved, render-ready material for the viewer */
            material: components["schemas"]["GarmentMaterialDto"];
            /** @description Owner asked for this look to appear in the gallery */
            publishRequested: boolean;
            /** @enum {string} */
            status: "PENDING" | "APPROVED" | "REJECTED";
            isPublic: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PaginatedLooksResponse: {
            items: components["schemas"]["LookResponse"][];
            total: number;
            page: number;
            limit: number;
        };
        CreateLookDto: {
            /** @example Crimson tee */
            name: string;
            /** Format: uuid */
            garmentModelId: string;
            /**
             * Format: uuid
             * @description Saved color reference; its hex is snapshotted into the look. Omit to use colorHex directly.
             */
            colorId?: string;
            /**
             * @description Ad-hoc color; required when colorId is omitted.
             * @example #2a9d8f
             */
            colorHex?: string;
            /** Format: uuid */
            patternId?: string;
            /** @default 1 */
            patternScale: number;
        };
        UpdateLookDto: {
            /** @example Crimson tee */
            name?: string;
            /** Format: uuid */
            garmentModelId?: string;
            /**
             * Format: uuid
             * @description Saved color reference; its hex is snapshotted into the look. Omit to use colorHex directly.
             */
            colorId?: string;
            /**
             * @description Ad-hoc color; required when colorId is omitted.
             * @example #2a9d8f
             */
            colorHex?: string;
            /** Format: uuid */
            patternId?: string;
            /** @default 1 */
            patternScale: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteMeDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminUsersController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Only items owned by the caller (cabinet view) */
                mine?: boolean;
                /** @description Email substring */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUsersResponse"];
                };
            };
        };
    };
    AdminUsersController_changeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserResponse"];
                };
            };
        };
    };
    AdminUsersController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModelsController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Only items owned by the caller (cabinet view) */
                mine?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedModelsResponse"];
                };
            };
        };
    };
    ModelsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelDetailResponse"];
                };
            };
        };
    };
    AdminModelsController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Only items owned by the caller (cabinet view) */
                mine?: boolean;
                status?: "PENDING" | "APPROVED" | "REJECTED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedModelsResponse"];
                };
            };
        };
    };
    ColorsController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Only items owned by the caller (cabinet view) */
                mine?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedColorsResponse"];
                };
            };
        };
    };
    ColorsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateColorDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColorResponse"];
                };
            };
        };
    };
    ColorsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatternsController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Only items owned by the caller (cabinet view) */
                mine?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPatternsResponse"];
                };
            };
        };
    };
    PatternsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePatternDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePatternResponse"];
                };
            };
        };
    };
    PatternsController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatternResponse"];
                };
            };
        };
    };
    PatternsController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatternResponse"];
                };
            };
        };
    };
    PatternsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatternDetailResponse"];
                };
            };
        };
    };
    PatternsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminPatternsController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Only items owned by the caller (cabinet view) */
                mine?: boolean;
                status?: "PENDING" | "APPROVED" | "REJECTED";
                confirmed?: boolean;
                requested?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPatternsResponse"];
                };
            };
        };
    };
    AdminPatternsController_moderate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatternResponse"];
                };
            };
        };
    };
    LooksController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Only items owned by the caller (cabinet view) */
                mine?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLooksResponse"];
                };
            };
        };
    };
    LooksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLookDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookResponse"];
                };
            };
        };
    };
    LooksController_gallery: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Only items owned by the caller (cabinet view) */
                mine?: boolean;
                /** @description Filter by saved color */
                colorId?: string;
                /** @description Filter by pattern */
                patternId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLooksResponse"];
                };
            };
        };
    };
    LooksController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookResponse"];
                };
            };
        };
    };
    LooksController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookResponse"];
                };
            };
        };
    };
    LooksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLookDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookResponse"];
                };
            };
        };
    };
    LooksController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminLooksController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Only items owned by the caller (cabinet view) */
                mine?: boolean;
                status?: "PENDING" | "APPROVED" | "REJECTED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLooksResponse"];
                };
            };
        };
    };
    AdminLooksController_moderate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookResponse"];
                };
            };
        };
    };
}
